// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zevsjmcajgdmbmywuxir.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpldnNqbWNhamdkbWJteXd1eGlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNjM2MTksImV4cCI6MjA3MTkzOTYxOX0.C323NOLZxOa9sr35WSwUDmtPFeETc_2thsoHt7Dk2Qk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});